[package]
name = "rewardverse"
version = "1.0.0"
authors = ["Meet Rathod"]

[addresses]
rewardverse= "0x36891e4a7f49c21b1fa4644112c1cdadf6a88c490e4b6d847d85bf6a24af3be2"
multisig = "0x502ec0500c9262a3c19afdffabc71e783252f32b8f5907f693e079fc5a16793a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
